inputdir: /fast/users/szyskam_c/work/downloads/NGSraw/200408-Twist2 # source of raw sequencing run data
workdir: /fast/users/szyskam_c/scratch/projects/AMLValidation # here your results are created
snakedir: /fast/users/szyskam_c/snakes/develop/targetSeq
samplesheet: /fast/users/szyskam_c/snakes/develop/targetSeq/sheets/TestRun2_sheet.csv
setup:
  cleanup:
    run: False
    keep_only_final_bam: True
  phred: 33
  run: Twist200408
  library: Twist-IDT  # have to be found at bed_files/SureSelect/<build>/SS_<library_version>_<build>_<Padded | Covered>[_nochr].bed
  library_version: IDT
  platform: illumina
  Flowcell: J3JGJ
  Instrument: M05651
  platform_unit: M05651.J3JGJ
  UMI: True  # if UMI information should be used in pipeline
  # if UMI_filter is true: deduplication is substituted with the UMI-filter pipeline
  # else: umi-aware deduplication is used 

#### ABSOLUTE PATHS ############
paths:
  mystatic: /fast/groups/ag_damm/work/ref/
  bihstatic: /fast/projects/cubit/current/static_data
  scripts: scripts/ # folder relative to snakedir
  filter_settings: /fast/users/szyskam_c/snakes/develop/somVarWES/info
#### REF SECTION ###############
ref:
  build: hg38
  hg19:
    genome_path: genome/gatk/b37
    genome: genome/gatk/b37/human_g1k_v37.fasta
    genome_split: genome/gatk/b37/split
    candidates: /fast/users/szyskam_c/work/utils/bulltools/known_sites/candidate_genes_aml.txt
    dbsnp: annotation/gatk/b37/dbsnp_138.b37.vcf
    dbsnp_all: annotation/gatk/b37/All_20180423.vcf
    dbsnp_common: annotation/gatk/b37/common_all_20180423.vcf
    gold_standard_indels: annotation/gatk/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
    phase1k_indels: annotation/gatk/b37/1000G_phase1.indels.b37.vcf
    # bed_file: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Covered_nochr.bed
    # bed_file_pad: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Padded_nochr.bed
  hg38:
    genome_path: genome/gatk/hg38/
    genome: genome/gatk/hg38/hg38.fasta
    genome_split: genome/gatk/hg38/split
    dbsnp: annotation/gatk/hg38/dbsnp_138.hg38.vcf
    dbsnp_all: annotation/gatk/hg38/All_20180418.vcf
    dbsnp_common: annotation/gatk/hg38/common_all_20180418.vcf
    gold_standard_indels: annotation/gatk/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf
    phase1k_indels: annotation/gatk/hg38/1000G_phase1.snps.high_confidence.hg38.vcf # seems to work instead of indels (acc. to GATK blog: https://gatkforums.broadinstitute.org/gatk/discussion/6800/known-sites-for-indel-realignment-and-bqsr-in-hg38-bundle)
    bed_file: bed_files/Twist/hg38/DKMS_v5_hg38.bed
    # bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
#### TOOLS SECTION ##############
tools:
  gatk: gatk # 
  gatk3: java -jar /fast/users/szyskam_c/work/utils/gatk3.8/GenomeAnalysisTK.jar -T
  # annovar: perl /fast/users/szyskam_c/tools/annovar2018
  annovar: perl /fast/users/szyskam_c/tools/annovar2019
scripts:
  split_fastq: shell/split_fastq.mawk
  prettifyBED : shell/prettify_BEDcoverage.awk
  anno_format: shell/anno_format.mawk
  vcf2table: shell/vcf2table.mawk
  cleanpileup: shell/cleanpileup.mawk
  anno_info: shell/anno_info.mawk
  csv2bed: shell/csv2bed.mawk
  pon2cols: shell/pon2cols.mawk
  cleanpileup: shell/cleanpileup.mawk
  pile2count: shell/pile2count.mawk
  matrix2EBinput: shell/matrix2EBinput.mawk
  makeponlist: shell/makeponlist.sh
  reducematrix: shell/matrix_minus_sample.mawk
  reordermatrix: shell/reorder_matrix.mawk
demulti:
  extract:
    read_structure: 151T8B9M8B151T
    mismatch: 5
    min_dist: 2   # minimum difference in mismatch to next-best hit 
    max_no_calls: 4  # maximum number of adjacent Ns in barcodes (I think)
    threads: 10
    max_mem: 5
  demulti:
    threads: 24
    max_mem: 20
fastq:
  threads: 20
qc:
  samplefactor: 1
ubamXT:
    threads: 8
    use_jdk: True # use_jdk_in/deflater to avoid SIGSEV error
map_ubam:
  threads: 16
  clip_overlap: False
  strategy: MostDistant  # alignment strategy for MergeBamAlignment
  use_jdk: True
bamindex:
  threads: 2
tag_bam: # needs enough RAM for loading entire uncompressed index fastq into memory
  run: True
  max_mem: 30g # memory for java VM (30g seems neccessary - needs to be smaller than threads * vmem/thread)
resplit_bam:
  threads: 20
dedup:
  threads: 4
dedup_umi:
  max_mem: 10g
  keep_dups: True # keep dups if you want to perform UMI-correction
realignGATK:
  threads: 16
recalib:
  run: True
  threads: 12
  known_sites: dbsnp_common   # which dbsnp database to use beside gold_standard_indels and phase1k
UMI_filter:
  run: True # if False and setup-->UMI is True, run umi-dedup
  min_reads:  1 # for WES-data, 1 is good; for targeted >3  counts for all fgbio tools
  group:
    threads: 10
    mem: 2G
    group_strategy: adjacency
    min_base_Q: 10
    min_map_q: 10
    allow_non_PF: True
    edits: 1  # 1 edit in a umi-node should be ok
  call:
    threads: 6
    mem: 6G
    error_rate_pre_umi: 45
    error_rate_post_umi: 40
    min_input_Q: 10 # input base quality (10 is default; IDT says 30)
  remap:
    threads: 10
    mem: 6G
    clip_overlap: True
    clip_adapters: True
  filter:
    threads: 6
    mem: 6G
    max_error_rate_per_read: 0.05
    max_error_rate_per_base: 0.1
    min_Q: 10 # input base quality
    max_no_call: 0.1 # fraction of reads filtered per M/e
bam_metrix:
  threads: 6
  bait: bed_files/Twist/hg38/DKMS_v5_hg38.bed # path relative to ref folder
  target: bed_files/Twist/hg38/DKMS_v5_hg38.bed # path relative to ref folder
mpileup:
  Q: 20   # base quality
  MAPQ: 10 # -q in pileup
freebayes:
  threads: 20
  use-bed-file: False
  min-alternate-count: 3
  min-alternate-fraction: 0.005
  Q: 10 # min base quality
  Qsum: 0 # min base quality sum to be considered supporting read
  MAPQ: 15 # min mapping quality
  mm_Q_limit: 10 # minimum base quality of mismatched read to be considered in mm_count_limit or max_mm_frac
  max_mm_frac: 1.0 # allowed fraction of mismatches in single read
  mm_count_limit: 0 # allowed number of mismatches per read
annovar:
  threads: 10
  path_to_humandb: annotation/annovar/humandb
  annofiles:
    - refGene
    - cytoBand
    - genomicSuperDups
    # - esp6500_all
    - esp6500siv2_all  #
    # - 1000g2010nov_all
    - 1000g2014oct_all
    - gnomad_exome_all
    # - gnomad_af.lna # not indexed
    # - exac03_all
    # - dbscsnv11
    # - snp131
    # - snp131NonFlagged
    - snp138
    - snp138NonFlagged
    - avsnp138
    - avsnp150
    - cosmic70
    - cosmic90
    # - clinvar_20150629
    # - clinvar_20170905
    - clinvar2019_short
    # - ljb26_all
    # - dbnsfp30a
    - dbnsfp35a
    - spidex
    - icgc29
Fisher_strand:
  threads: 20
filter:
  threads: 2
  min_read_depth: 100
  min_TR2: 5
  filter_settings: filter_AML.csv
  edit:
    extended_output: False
    candidate_list: annotation/damm_lists/AML_candidates.txt
    driver_list: annotation/damm_lists/AML_drivers.txt
    hotspot_list: annotation/damm_lists/CHIP_mutations_short_hg38.csv
  filter_name: damm
  run: True
  filter1: damm1.py
  filter2: damm2.py
  keep_syn: False
filter_bam:
    threads: 4
    stringency_for_IGVnav: moderate
    padding: 200
    folder: filterbam
primer3:  # is applied after filter step 1
  threads: 10
  min_size: 120
  max_size: 220
  center_offSet: 5 # how much offSet primer pairs can
  use_primer_list: ''
HDR:
  threads: 2
  min_HDR_count: 1 # minimum lanes around mutation to make it a putative HDR
  min_similarity: .85 # which similarities to consider as HDR
  padding: 150  # range around mutation to be scanned
  min_q: 20 # minimum base quality to be used for HDR-calculation